
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

# Current configuration:
# - django 2.2, python 3.6, wagtail 2.5
# - django 2.2, python 3.7, wagtail 2.7
# - django 3.0, python 3.8, wagtail 2.10
# - django 3.1, python 3.8, wagtail 2.11
# - django 3.1, python 3.9, wagtail master (allow failures)
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - python: 3.6
            django: "Django>=2.2,<2.3"
            wagtail: "wagtail>=2.5,<2.6"
            experimental: false
          - python: 3.7
            django: "Django>=2.2,<2.3"
            wagtail: "wagtail>=2.7,<2.8"
            experimental: false
          - python: 3.8
            django: "Django>=3.0,<3.1"
            wagtail: "wagtail>=2.10,<2.11"
            experimental: false
          - python: 3.8
            django: "Django>=3.1,<3.2"
            wagtail: "wagtail>=2.11,<2.12"
            experimental: false
          - python: 3.9
            django: "Django>=3.1,<3.2"
            wagtail: "git+https://github.com/wagtail/wagtail.git@master#egg=wagtail"
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
          pip install -e .[testing]
      - name: Test
        run: ./runtests.py
